services:
  - type: web
    name: mlb-pinnacle-tracker
    env: python
    buildCommand: pip install -r requirements. text
    startCommand: uvicorn main: app --host 0.0.0.0  --port $PORT
    disk:
      name: snapshots-db
      mountpath: /data
      sizeGB: 1
